name: Pipeline de Integração Contínua (CI/CD)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependências do Backend
      run: |
        cd backend
        npm install

    - name: Executar Testes Automatizados (Jest)
      run: |
        cd backend
        npm test

    
    - name: Login no Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}gi
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Construir e Publicar a Imagem do Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/hardware-backend:latest
          ${{ secrets.DOCKER_USERNAME }}/hardware-backend:${{ github.sha }}